# syntax=docker/dockerfile:1

FROM composer:2 AS vendor
WORKDIR /app
ENV COMPOSER_ALLOW_SUPERUSER=1

COPY composer.json composer.lock ./
RUN composer install --no-dev --no-scripts --no-autoloader

COPY . .

RUN composer install --no-dev --optimize-autoloader --no-scripts

FROM dunglas/frankenphp:1-php8.4-alpine

WORKDIR /app
ENV APP_ENV=prod
ENV APP_DEBUG=0

COPY --from=vendor /app /app

EXPOSE 8080

CMD ["frankenphp", "run", "--config", "/app/docker/frankenphp/Caddyfile"]
