schemaVersion: 2
environments:
  prod:
    id: prod
    runtime: cloud
    boot:
      script: _deploy/hooks/cloud-boot.sh
    deploy:
      presets:
        - aws/secure-edge
        - aws/minimal-http
