schemaVersion: 2
environments:
  dev:
    id: dev
    runtime: docker
    docker:
      composeFile: _docker/docker-compose.yml
      service: app
      url:
        scheme: http
        domain: localhost
        port: "{{localPort}}"
      commands:
        make-migrations:
          label: Make migration(s)
          command: php bin/console make:migration --no-interaction
        migrate:
          label: Run migrations
          command: php bin/console doctrine:migrations:migrate --no-interaction
        clear-cache:
          label: Clear cache
          command: php bin/console cache:clear --no-interaction
    vars:
      localPort:
        required: true
        default: "8080"
      localDbPort:
        required: true
        default: "5432"

  staging:
    id: staging
    runtime: cloud
    boot:
      script: _deploy/hooks/cloud-boot.sh
    deploy:
      presets:
        - aws/cheap-and-cheerful
        - aws/maximum-effort-at-a-price
        - digitalocean/app-platform-default

  prod:
    id: prod
    runtime: cloud
    boot:
      script: _deploy/hooks/cloud-boot.sh
    deploy:
      presets:
        - aws/cheap-and-cheerful
        - aws/maximum-effort-at-a-price
        - digitalocean/app-platform-default
