happycode_tenzero_auth:
  app_name: "Happy Coder"
  app_description: "Auth done the Happy way!."
  user_class: 'App\Entity\User'
  user_field: "email"
  theme: "tz-theme-default" # or tz-theme-vibes
  enable_register: true
  register_fields: ["firstname", "lastname"]
  login_redirect_url: "/private"
  logout_redirect_url: "/bye"
  token_ttl: 60 # seconds
  api_route_path: "/api"
  access_control:
    - { path: "^/bye", roles: "PUBLIC_ACCESS" }
    - { path: "^/$", roles: "PUBLIC_ACCESS" }
    - { path: "^/", roles: "IS_AUTHENTICATED_FULLY" }
