schemaVersion: 2
environments:
  dev:
    id: dev
    runtime: docker
    docker:
      composeFile: _docker/docker-compose.yml
      service: app
      url:
        scheme: http
        domain: localhost
        port: "{{localPort}}"
    vars:
      localPort:
        required: true
        default: "8080"

  uat:
    id: uat
    runtime: cloud
    boot:
      script: _deploy/hooks/cloud-boot.sh
    deploy:
      presets:
        - aws/minimal-http
        - aws/secure-edge

  prod:
    id: prod
    runtime: cloud
    boot:
      script: _deploy/hooks/cloud-boot.sh
    deploy:
      presets:
        - aws/minimal-http
        - aws/secure-edge
