schemaVersion: 3
environments:
  local:
    id: local
    runtime: docker
    docker:
      composeFile: _docker/docker-compose.yml
      url:
        scheme: http
        domain: localhost
        port: "{{localPort}}"
      commands:
        - clear-cache:
          run:
            - label: Clear cache
            - command: "php bin/console cache:clear --no-interaction"
        - migrate-database:
          run:
            - label: Migrate database
            - command: "php bin/console doctrine:migrations:migrate --no-interaction"
        - load-fixtures:
          run:
            - label: Load fixtures
            - command: "php bin/console hautelook:fixtures:load --no-interaction"
    vars:
      DATABASE_URL:
        required: true
        secret: true
      APP_MODE:
        required: true
        default: dev

  uat:
    id: uat
    runtime: cloud
    boot:
      script: _deploy/hooks/cloud-boot.sh
    vars:
      DATABASE_URL:
        required: true
        secret: true
      APP_MODE:
        required: true
        default: prod
    deploy:
      presets:
        - aws/cheap-and-cheerful
        - aws/maximum-effort-at-a-price
        - digitalocean/app-platform-default

  prod:
    id: prod
    runtime: cloud
    boot:
      script: _deploy/hooks/cloud-boot.sh
    vars:
      DATABASE_URL:
        required: true
        secret: true
      APP_MODE:
        required: true
        default: prod
    deploy:
      presets:
        - aws/cheap-and-cheerful
        - aws/maximum-effort-at-a-price
        - digitalocean/app-platform-default
