environments:
  local:
    id: local
    runtime: docker
    docker:
      composeFile: _resources/_docker/docker-compose.yml
      url:
        scheme: http
        domain: localhost
        port: 8000
        # path: /app
        # query: debug=true
    vars:
      DATABASE_URL:
        required: true
        secret: true
      APP_MODE:
        required: true
        default: local

  base-cloud:
    id: base-cloud
    abstract: true
    runtime: cloud
    vars:
      DATABASE_URL:
        required: true
        secret: true
      APP_MODE:
        required: true
        default: prod

  prod:
    id: prod
    extends: base-cloud
    deploy:
      targets:
        aws:
          engine: opentofu
          source: _resources/_deploy/opentofu-aws.tf
        digitalocean:
          engine: opentofu
          source: _resources/_deploy/opentofu-do.tf
