FROM php:8.4-fpm-alpine

# Install system dependencies
RUN apk add --no-cache \
    git \
    curl \
    libpng-dev \
    oniguruma-dev \
    libxml2-dev \
    zip \
    unzip \
    postgresql-dev \
    icu-dev

# Install PHP extensions
RUN docker-php-ext-install pdo_pgsql mbstring exif pcntl bcmath gd intl

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install \
  --prefer-dist \
  --no-interaction \
  --no-dev \
  --optimize-autoloader \
  --no-scripts

COPY _deploy/hooks /opt/partrocks/hooks
RUN chmod +x /opt/partrocks/hooks/*

COPY . .

EXPOSE 9000
CMD ["php-fpm"]